### ISSUE TITLE
HLW 3: What Factors Motivate Students to Learn?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#100]

**Comment by weaverbel** [comment]
The claim that *'People learn best when they care about the topic and believe they can master it'* relates to what *HLW* calls 'value' and 'expectancies'. People are motivated to master something that will add value by meeting  goals they have such as learning goals (enjoyment of mastery for its own sake), and performance goals (passing a subject, getting a good mark). Expectancies are about their belief in their ability to achieve goals. 

The *"teach most immediately useful first"* concept relates to establishing that value early on and supporting learners' expectancies of being able to grasp the material so that the motivation that got them to the workshop is not dissipated by tasks that either seem too hard or are not immediately relevant.

The demotivating bugbears of *"indifference, unfairness, and elitism"* are covered by the code of conduct which should help establish the belief that learners are in a supportive environment - one that will help them learn. The sticky note system helps them understand "there are no stupid questions" and the nature of live coding shows the instructor struggles just as much as they do with errors. All of these should reinforce the sense of safety for learners.

Given that we try to to have our instructors understand through the training 

1) the need to establish value, 
2) provide a welcoming and supportive environment, and 
3) not to stifle expectations 

by making tasks too hard, talking at too detailed a level, or by moving too quickly without seeking understanding along the way, I think we have covered most of the important issues in the *HLW* chapter about motivation. I don't' see that much is missing. I think the material as taught does the job of addressing the important points.

**Comment by gvwilson** [comment]
Hi @weaverbel - can you please turn this into a 10-point list for addition to reference.md? There are examples in there to use as a model.
