### ISSUE TITLE
HLW 5: What Kinds of Practice and Feedback Enhance Learning?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#102]

**Comment by uiuc-cse** [comment]
## Ten Neglected (Or Underutilized) Points

10.  Mismatched expectations can be difficult to diagnose and waste much time.
9.  In the absence of structure, learners tend to glide along more comfortable paths (i.e., making slides prettier rather than more content-rich).
8.  Deliberate practice without effective feedback can instill new unknown bad habits.
7.  "Learning and performance are best fostered when students engage in practice that
    1.  focuses on a specific goal or criterion for performance,
    2.  targets an appropriate level of challenge relative to students’ current performance, and
    3.  is of sufficient quantity and frequency to meet the performance criteria."
6.  Articulate goals in measurable ways (use good metrics that relate to the objective and to possible performance from the learner)—include higher-level goals.
5.  Concurrent learning can work, but often not at the novice skill level.  (This is my interpretation of p. 131.)
4.  While quality of practice matters, time on task is also important.
3.  Practice tends to be most effective at improving skills in the "competent" range.  (This relates to the bit I said in the teaching about novices facing known knowns, competents facing known unknowns, and experts facing unknown unknowns.)
2.  Instructors should point out progress as it is made so that students recognize their accomplishment and discern the change in their behavior, especially when gradual.
1.  "Although grades and scores provide some information on the degree to which students’ performance has met the criteria, they do not explain which aspects did or did not meet the criteria and how."  More specific feedback is necessary.  Pp. 139ff. reminded me of this passage in [HPMoR](http://hpmor.com/):  "And on the rare occasions I offer you a written test, it will mark itself as you go along, and if you get too many related questions wrong, your test will show the names of students who got those questions right, and those students will be able to earn ... points by helping you."

**Comment by davis68** [comment]
C'est moi—I honestly need to just use two browsers for GitHub...

**Comment by gvwilson** [comment]
Thanks Neal - I'll fold these into a reference guide.
