### ISSUE TITLE
Could we build a Web -based checkout process?

### ISSUE THREAD

**Issue by weaverbel** [swcarpentry/instructor-training#122]
Rather than use emails and etherpads for stepping people through the final stages, could we build some kind of web service where they can step through it instead? As they progress from doing the pull request through signing up for and attending the discussion session to signing up for and then attending the final practice teaching sessions, they and/or the checkout person or mentor could tick the stage off as it's done, and the person could see their progress, and then finally they're there? Not sure how much work this would be but people have grumbled to me about trying to find out what to do next - rummaging back through emails etc. If it was all online, this would be easier on everyone. But maybe this would be a huge overhead and not practical. Happy to be shot down.

**Comment by gvwilson** [comment]
Yes - there's a discussion thread at 
https://github.com/swcarpentry/board/pull/81 about this, since we're 
hoping to get a Google Summer of Code student to work on it this summer 
(or winter, if you're in Australia).  Please add comments to that thread 
- I'd be very grateful for input on what the process and interface 
should look like.

**Comment by weaverbel** [comment]
Have lodged it there now.
