### ISSUE TITLE
Stereotype threat is maybe, possibly... not a thing?

### ISSUE THREAD

**Issue by arokem** [swcarpentry/instructor-training#124]
I am not sure what to make of it: http://psychbrief.blogspot.co.uk/2015/12/thats-not-quite-right-stereotype-threat.html

**Comment by alistairwalsh** [comment]
As this is something we teach, I think we should find the studies that are being referenced and look into this a little further.

Brain plasticity was discounted for many years before it was finally accepted, because it was a well known fact “that the brains of adults are set"




> On 11 Mar 2016, at 12:16 PM, Ariel Rokem <notifications@github.com> wrote:
> 
> I am not sure what to make of it: http://psychbrief.blogspot.co.uk/2015/12/thats-not-quite-right-stereotype-threat.html <http://psychbrief.blogspot.co.uk/2015/12/thats-not-quite-right-stereotype-threat.html>
> —
> Reply to this email directly or view it on GitHub <https://github.com/swcarpentry/instructor-training/issues/124>.
> 

Alistair Walsh 


BSc (Hons) Cognitive Neuroscience
alistair.walsh@unimelb.edu.au <mailto:alistair.walsh@unimelb.edu.au> @alistairwalsh

Research Community Coordinator
Research Platforms Training Services
University of Melbourne
melbourne.resbaz.edu.au <http://melbourne.resbaz.edu.au/> | @ResPlat

Training calendar: melbourne.resbaz.edu.au/calendar <http://melbourne.resbaz.edu.au/calendar>

Facebook Groups: NeuralCode <https://www.facebook.com/groups/NeuralCode/>

**Comment by gvwilson** [comment]
Ariel and Alistair, can you please take this one on and do a PR? It's OK 
for us to say "this is currently being debated" - our audience will (or 
should) understand that science is a process of groping towards a higher 
level of confusion...

**Comment by arokem** [comment]
I think I managed to convey a very high level of confusion on this
particular topic, as I was teaching it yesterday :-)

I think also the points about *what to do* about stereotype threat are hard
to explain and hard to implement.

This blog post is really helpful in that regard:
https://dynamicecology.wordpress.com/2014/04/29/countering-stereotype-threat/

Might do a PR, when I get from under everything, but if someone else wants
to take a stab, please do!

**Comment by apawlik** [comment]
Just to add something to the discussion which I learnt from Andre Geldenhuis of Victoria University, [Teaching Stereotype Threat as a Means of Improving Women's Math Performance](http://pss.sagepub.com/content/16/3/175.abstract)

**Comment by alistairwalsh** [comment]
I just had a look at the article 
"Knowing Is Half the Battle: Teaching Stereotype Threat as a Means of Improving Women's Math Performance."
Psychological Science March 2005 16: 175-179,

And there are a couple of claims that I have questions about.

###Removing non-Caucasian students after results were gathered.

They state 
"We analyzed the performance of White participants only because of evidence that gender differences in math performance exist only among Caucasian students (Hyde, Fennema, & Lamon, 1990). This led to the exclusion of 27 participants, leaving a final sample of 75 women and 42 men."

This means they recruited non-Caucasian participants despite the evidence that "gender differences in math performance exist only among Caucasian students". This says to me that after analysing the results and finding no significant difference between the performance of men and women, they looked for ways to get a significant difference and then found citations to support what they had to do. This idea is further supported by the difference in group numbers 75:42 after the manipulation (which makes anova more difficult than if the groups have equal numbers).

###Is the presence of gender stereotype the only difference between conditions?


This section where they describe the conditions (italics mine)
"In the problem-solving condition, the researcher informed participants that they would be asked to complete a _problem-solving exercise_ for a study of general aspects of cognitive processes. In the math-test condition, participants were told that they would be completing a _standardized test for a study of gender differences in mathematics performance_. In the teaching-intervention condition, participants were given the _same instructions as in the math-test condition_. In addition, the researcher described stereotype threat and suggested to women that ‘‘it’s important to keep in mind that if you are feeling anxious while taking this test, this anxiety could be the result of these negative stereotypes that are widely known in society and have nothing to do with your actual ability to do well on the test.’’

This means that there was a major difference in how the task was described - Problem solving v.s. Maths. Have a look at the results again and you can see that it could be that women perform better if "Maths" is not mentioned _or_ men perform worse if "problem solving" is mentioned _or_ a bit of both.

I suggest this because we live in a gendered society with most tasks being delegated to a gender group based on assumed masculine and feminine traits. There is another concept called "Social desirability" which has to do with wanting to be seen in a favourable light by others. It is possible that being good at "Math" is seen as a masculine trait and that being good at "problem solving" is seen as a feminine trait and both genders wanted to fit their chosen gender role in a situation where there are no other consequences. 

[Psychological Science-2005-Johns-175-9 copy 2.pdf](https://github.com/swcarpentry/instructor-training/files/171390/Psychological.Science-2005-Johns-175-9.copy.2.pdf)

**Comment by patitsas** [comment]
Part of the issue with stereotype threat is it hasn't been consistently defined in the literature. For example, Shapiro and Neuberg list six different "stereotype threats" that have been conflated together in the literature: http://www.europhd.net/html/_onda02/07/PDF/20th_lab_materials/jane/shapiro_neuberg_2007.pdf

Environmental cues can have massive effects on demotivating students who are minority members. As I understand the psych literature it's not clear that stereotype threat is the/a mechanism which causes this demotivation. Doesn't mean the demotivation doesn't happen!

I think it's possible to have a meaningful discussion about this in the workshops without having to bring in the words "stereotype threat".

**Comment by gvwilson** [comment]
From Elizabeth Patitsas:

The research on Stereotype Threat is looking pretty weak these days. There’s still lots of evidence that unwelcoming climates demotivate minorities -- it’s just not clear that stereotype threat is the underlying mechanism. (Indeed, “stereotype threat” as Steele talks about it has been picked apart as actually being six different stereotype threats that he conflates repeatedly.) I’d spend that space on talking about, for example, Barker’s work on defensive climates, and how classroom climate affects minorities. You don't need the words stereotype threat to talk about this.

The “positive, successful role models from their group” thing is in many cases counterproductive! See: http://spp.sagepub.com/content/early/2012/03/27/1948550612440735

Talking about subtyping, in-group favouritism and the out-group homogeneity effect would be worth mentioning, particularly in terms of why minorities (the out-group) have a hard time and why it's hard to change that fact. I’ve got a blog post on this that you might find helpful: http://patitsas.blogspot.ca/2013/11/subtyping-subgrouping-and-stereotype.html 

**Impostor Syndrome**

I’d recommend having a read of this recent article on how the emphasis on things like impostor syndrome makes minority members feel like the problem is them rather than the system that causes them to feel that way: https://modelviewculture.com/pieces/how-the-rhetoric-of-imposter-syndrome-is-used-to-gaslight-women-in-tech

I think in any discussion of diversity it's worth talking about the difference between the deficit model (we need to change the minority people because they have some deficit, e.g. lack of prior experience) vs. a systems approach (we need to change the system because it produces these disparities).

**Comment by gvwilson** [comment]
Anyone want to take this one through to completion?
