### ISSUE TITLE
Addressing issues from Elizabeth Patitsas's post

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#130]
http://patitsas.blogspot.ca/2016/03/women-in-computing-as-problematic.html

**Comment by alistairwalsh** [comment]
Very interesting read about an unpublished (read: not peer reviewed) thesis. I am reluctant to comment on the experience of females in this area, as I have no direct experience of what this is like. One section did resonate with me - 
"Female Friendly Education?

A particular session stood out for Sturman, titled "'Female Friendly Education: Increasing Participation or Watering Down?' provoked a heated response from audience members, many of whom were university students and professors. The topic unexpectedly made clear how the insertion of diverse women into a generalized female identity in 'women in computing' or 'female friendly Computer Science' is extremely problematic, constituting a unitary subject which also produces those it does not include as marginal. Among the panelists, Sue Rosser, a feminist scholar of science at Georgia Tech, had coined the term 'female friendly science’ (1990) to signify a new approach to university science education which would take into account how science is gendered and would seek to redirect values and practices in scientific work to reflect the interests and experiences of women as well as men."

"Certainly, in the group of female graduate CS students I interviewed, the majority resisted the characteristics ascribed to them in a ‘female friendly’ Computer Science approach, characteristics which positioned them as gendered subjects, read as less competent and less able in relation to the dominant unmarked male subject of Computer Science. The panelists presented their questions to the audience in an attempt to get feedback about why ‘third wave’ (their term) feminists and younger CS women in general responded negatively to the term ‘female friendly..."

"The practices of ‘female friendly’ science assemble a subject which is the Other, as the term ‘female friendly science’ itself acknowledges that the discipline of science limits the right of women to participate in its laws of discourse. Thus ‘female friendly science’ performs a reinscription of social exclusion. The existing forms of scientific discourse, or what the presenters described as masculinized STEM values, ‘an emphasis on truth, beauty and puzzles’, determine the limits by which femininized values of ‘time spent on community and social impact’ can be uttered as a ‘truth’ about women through the gender binary."

I have heard a young female SWCarpentry instructor echo those sentiments.
Her opinion was that labelling something as a "Women's Python Workshop" rather than just a "Python Workshop" implied that women needed extra help with programming and were not as inherently capable of learning programming as males. It was her opinion that all women needed was a fair go at it, without harassment or other negative conditions to deal with.

It is a difficult situation, and I do recognise the great work that the female only groups do to move us toward gender equality.

**Comment by patitsas** [comment]
One thing that has been substantiated by many studies beyond Sturman's is that the use of role models can be demotivating, not motivating. (e.g. http://spp.sagepub.com/content/3/6/738.short )

Women can be demotivated by seeing exceptionally successful and feminine female role models and think, "I could never be like her!" and conclude they need to be like her in order to succeed in CS/science.

Right now the lesson on motivation/demotivation says that instructors should "Expose students to positive, successful role models from their group." --- I think advice that simplistic could backfire. :\

**Comment by ErinBecker** [comment]
Would anyone like to take on incorporating these thoughts into the Motivation/Demotivation episode? 

Due to a lack of activity, this issue will be closed on 3/14/17 if no comment by then.

**Comment by ChristinaLK** [comment]
I do think we should make the change suggested by @patitsas, own this one to me.

**Comment by ChristinaLK** [comment]
Already been addressed, apparently.
