### ISSUE TITLE
Combining different teaching techniques

### ISSUE THREAD

**Issue by apawlik** [swcarpentry/instructor-training#177]
Over the course of IT we try to combine different techniques that we introduce (concept maps as a form of formative assessment, feedback on the sticky notes/minute cards to take immediate action and improve your teaching and so on.
It creates a flow, shows people that there is a logic in all this :-)

On that note: an interesting (in my opinion) paper showing how to combine formative assessment with faded examples http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=4116999&tag=1 (sorry for the paywall but I think unpaywalled version is available).

**Comment by ErinBecker** [comment]
@apawlik This looks like an interesting paper. Would you like to take a stab at incorporating these thoughts into the curriculum? Or maybe we could start a resource library for related readings that interested trainees could look at. 

Please let me know what you'd like to do with this issue. Due to a lack of activity, this issue will be closed on 3/14/17 if no comment by then.

**Comment by ErinBecker** [comment]
Closed due to lack of activity.
