### ISSUE TITLE
Add explicit description of programming skills required by trainees

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#205]
Recent participant pointed out that we don't explicitly say what programming skills participants require.

**Comment by ErinBecker** [comment]
I noticed this too, but assumed it was intentional because of the wide range of skills possible (e.g. different skills needed to teach the spreadsheets/open refine DC ecology lessons than the bash shell or git lessons). 

If we add "required programming skills", I strongly suggest we keep this as open as possible and communicate that it will vary across lesson/workshop types. I also suggest that we include some sort of statement encouraging people who are still developing their skills to consider going through instructor training anyway. We as a community can help provide resources to get people "up to speed" in a specific skill. Much more important to attract dedicated people who are willing to learn and are aligned with the Carpentry vision.

**Comment by gvwilson** [comment]
Apologies - this is meant to be "programming skills required to take 
instructor training", i.e., what (if anything) participants need in the 
two days.

**Comment by ErinBecker** [comment]
Ah. So, not meant to cover what programming skills people need to have in order to *be* instructors? Isn't the answer to the question "what programming skills do you need to go through IT" just "none"?

**Comment by gvwilson** [comment]
1.  One of the participants from two weeks ago said they'd have been 
less stressed if they knew that before coming in - they thought that 
they might need to be an expert programmer in order to become an instructor.
2.  The live coding exercise requires *some* programming skill - we used 
to always do it with the Unix shell, but thanks to Lex's example, we can 
be more general now.

**Comment by ErinBecker** [comment]
1. Good feedback! Always a good idea to clearly set expectations.
2. Right - had forgotten about that exercise.

**Comment by raynamharris** [comment]
Is there a way to see you need to be comfortable with 1 or more of the main topics we teach?  I came in only knowing R but eventually learned Unix and Git, and a few of my colleagues share a similar (only knew python or R at the start) story.  I know a handful of instructors that only ever teach one thing, so that seems like a minimum.
