### ISSUE TITLE
Inaccurate sentence about multi-channel input

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#212]
From @raynamharris:

```
I found the following sentence in http://swcarpentry.github.io/instructor-training/10-load/:

"Learning is therefore more effective when redundant information is not being presented simultaneously in two different channels."

However, in the live-coding section, we say that its easier for people to follow along when you say outside exactly what you are type. The reinforcement makes it easier because the student can listen, watch, and/or type simultaneously. 
```

**Comment by lexnederbragt** [comment]
So do you think we shouldn't offer the two channels during live-coding, or rephrase the part on cognative loading?

**Comment by ErinBecker** [comment]
My background isn't in cognitive psychology, but from what I've read, the problem with increased cognitive load from multiple channel information delivery comes about when the channels are *not* presenting the same information. In that situation, learners have to process both channels and the discrepancies between them. I would suggest rephrasing the cognitive loading material rather than the live-coding.

I'll pull up a paper or two for future references.

**Comment by ErinBecker** [comment]
Here's a [good summary](http://sorden.com/portfolio/sorden_draft_multimedia2012.pdf) of a classic textbook chapter on the subject. Unfortunately, I have the pdf of the original book chapter, but it's paywalled and also slightly corrupted (old, and not digitized correctly).

**Comment by raynamharris** [comment]
@lexnederbragt My thought was that the wording of the cognitive loading needed to be re-phrased. I think saying what you type is crucial to live coding!

**Comment by karinlag** [comment]
On 10/06/16 23:45, Rayna M Harris wrote:
> @lexnederbragt <https://github.com/lexnederbragt> My thought was that
> the wording of the cognitive loading needed to be re-phrased. I think
> saying what you type is crucial to live coding!

+1 to that!

Karin

**Comment by ErinBecker** [comment]
https://github.com/swcarpentry/instructor-training/blob/gh-pages/_episodes/11-load.md
