### ISSUE TITLE
reordering day 2 (again)

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/instructor-training#222]
What would people say to: 
* live coding
* break
* swc practices + motivation/demotivation
* lunch
* lesson objectives, lessons, live coding 2
* break
* the carpentries + assessment (if time)

In my mind, the whole second day is "what makes swc/dc unique?"  The morning is what we DO, bookended by our most important features (live coding and our emphasis on a safe, motivated learning environment) with the other practices + discussion of the CoC to bridge the two.  Afternoon is what we TEACH, talking about objectives generally, then the main objectives of the lessons (I really emphasized the best practices side of things today, which circles back to objectives nicely, I think), and then actual information about the orgs, checkout procedure, and how to assess our impact if you have time.  

Incorporates suggestion from #219 

Thoughts? Yea/nay?  If this is ok w/ people, I will submit the PR making the change.  :)

**Comment by ErinBecker** [comment]
Just finished training today and I can testify that folks were confused
about what the carpentries are and do all the way through. I think this
section needs to be sooner (ideally first) and not later.

Planning on looking at feedback as soon as it comes in to see if my reading
of the situation is correct.

I do like the idea of doing live coding twice though.

**Comment by ChristinaLK** [comment]
Now that you say that, we had similar feedback...

**Comment by gvwilson** [comment]
I used to open with an overview of the Carpentries, but it made for a slow start on day 1, since there's nothing really actionable (and opening with formative assessment is always a good early win). We could swap concept mapping to day 2, and do live coding + video + the Carpentries on the afternoon of day 1... ?

**Comment by raynamharris** [comment]
I'm really happy the way @ChristinaLK  worded Day 2 as being "what makes SWC DC unique". Day 1 is all about getting people to think about how to be a better teacher in general and day two is how to be a SWC DC instructor specifically. 

The only thing that I think was missing from our workshop was concise overview of the workshop at 9 am. like. "Today we cover teaching philosophy, tomorrow SWC DC philosophy, and then you will have to do a few things on your own time to become certified." This way, they know they have to wait but know its coming. At first I thought it was there, but then I realized that it is on the about page..

Now I'm wondering all the information in the "about this workshop" section on the home page could be put into a 3 min "welcome" episode before launching into the "introduction" episode.... @ErinBecker @gvwilson would that clarify the overview and better manage student expectations?

**Comment by ChristinaLK** [comment]
I said some of this - that day 1 was more general and day 2 was more swc/dc focused, but that's not in the notes themselves...I think it could be added at the beginning of  the intro.

**Comment by lexnederbragt** [comment]
Is there going to be enough time when you add in another slot of live coding?

**Comment by ErinBecker** [comment]
In the UA training, the "Intro to the Carpentries" module took 20 minutes. We certainly don't need all of this info immediately at the start of the first day of training, but a short, succinct "who we are and what our purpose is" could easily fit into a 3 min "welcome" episode like @raynamharris suggested.

@raynamharris - I assume the thumbs down on my post above was a mis-click? :-(

**Comment by ErinBecker** [comment]
With respect to doing live coding twice, there's a lot of good argument for this. 

a) It gives more practice on teaching practices that we expect them to be doing during our workshops (so it's authentic). 
b) On top of that, it *feels* more like what many of the instructors are saying is missing from training (focus on SWC/DC specific instructional practices and content) - so it could help us with buy-in for the training and feelings of fulfilled expectations. Even though the live coding exercise isn't *about* the specific part of the lesson that is being used (in our case, pipes), it gives them a better taste of what our material looks like. 
c) Iterative practice is always more effective than single practice, and since live coding is the core carpentry instructional practice, if we're going to iterate on anything, it should be this.

@lexnederbragt raises the ever-present question of what do we take out. Greg and I very briefly debriefed this morning about yesterday's training and I think are in agreement that it would be good to:  

- restructure the content so that the relationship between different content modules is more obvious (currently it feels to me like a lot of relatively disconnected good ideas about teaching)  and
- beef up the practice/authentic task components by distributing them more evenly throughout the time.  

To this, I would add (and I don't know if we're in agreement on this yet) that there are portions of the content that, while being very good and sound pedagogical practices, aren't the most useful way for us to be spending our limited time with our instructors. I'll organize my notes a bit more today and make some more concrete suggestions about what specifically we can consider cutting to make room for more practice/tasks.

**Comment by ChristinaLK** [comment]
I think Rayna did a nice job of working in authentic tasks as we went, especially on Day 2.  

Also, I think Rayna and I would have had time to do another round of live coding for our training (we finished 30 min early), so I can look through the notes and see what we glossed over to figure out where that time came from.

**Comment by raynamharris** [comment]
I was trying to say thumbs down to moving the carpentries to day 1, although now I see that it wasn't specifically proposed. (Thumbs down removed :) @ErinBecker)

@lexnederbragt, we didn't have the students make a website, so that's one thing that could be cut. We also finished early, so there was time if we had thought of it a little bit early. On the other hand, I talk very fast and my stories/answers are brief, so I could have added a second round of live coding without cutting anything...

**Comment by karinlag** [comment]
I think that we need to tell them (quickly) on the first day what´s unique about us and what kind of teaching we are teaching them to do. That way they will (ideally at least) reflect on what we teach them in the light of what kind of teaching we want them to do. I think they will then reflect on the differences they see between us and the kind of teaching they´ve been exposed to before, and hopefully understand more of what we are about.
