### ISSUE TITLE
Add more on teaching practices from Lemov

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#224]
From @ErinBecker:
- Cold call
- Stretch-it
- No apology
- Circulate
- Normalize Error
- Praise Effort
- Praise Improvement
- Right is Right

**Comment by ErinBecker** [comment]
Since Lemov's whole schtick is that you don't learn something by talking about it, but by practicing it in a specific setting (check out his other book [Practice Perfect] (https://www.amazon.com/Practice-Perfect-Rules-Getting-Better/dp/111821658X/ref=sr_1_1?ie=UTF8&qid=1465593180&sr=8-1&keywords=practice+perfect+doug+lemov)), I strongly recommend against adding a section where we talk about these techniques. If we're going to incorporate these materials (which would be great!), we should pick a couple that are highly relevant to our teaching context and drill on them. I have drills developed for all but Normalize Error, Praise Effort, and Praise Improvement. Those three are probably highly relevant to our context, I just don't have drills tested yet.

**Comment by lexnederbragt** [comment]
Where do I go to get a feeling for what these practices are about?

**Comment by ErinBecker** [comment]
The main source would be Lemov's book "Teach like a Champion", but for a
summary, check out
http://massp.org/downloads_massp/the_main_idea/teach_champion.pdf

On Sat, Jun 11, 2016 at 12:40 AM, Lex Nederbragt <notifications@github.com>
wrote:

> Where do I go to get a feeling for what these practices are about?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/swcarpentry/instructor-training/issues/224#issuecomment-225342631>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSbfwxpHnMdgneH2re7V7BHiTc2nc_Tks5qKmZ4gaJpZM4Iy0yL>
> .
>



-- 
*Erin Becker*, PhD
Data Carpentry, Associate Director
http://www.datacarpentry.org/
Research Associate, MMG Dept., UC Davis

**Comment by ErinBecker** [comment]
@gvwilson I'm not a fan of adding things piecemeal. Let's figure out whether this fits in with the overall goals for instructor training, and if so where. If we know what our objectives are for adding this, I'd be more than happy to help draft this up.

**Comment by gvwilson** [comment]
The massp.org URL 404's for me.

**Comment by lexnederbragt** [comment]
Strange, I think I downloaded it from there just last week... Google led me to http://www.themainidea.net/tmi_pdfs2/THE%20MAIN%20IDEA%20--%20Teach%20Like%20a%20Champion%20--%207-10(2).pdf (same PDF).
