### ISSUE TITLE
Add material from Glassman's essay

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#227]
https://medium.com/@roboticwrestler/insights-from-educational-psychology-and-cognitive-science-that-can-help-us-teach-all-students-how-b34e43c7d247#.msikpxuen

**Comment by ErinBecker** [comment]
Topics that would integrate well include:
- self-explanation
- deliberate practice
- scaffolding
- analogical learning
- variation theory

I'd be happy to bring some of these concepts into the IT materials within the next few work cycles. Please let me know if anyone would like to help with this.

**Comment by ChristinaLK** [comment]
I'm happy to review PRs and talk about where this material might go.

**Comment by ErinBecker** [comment]
@ChristinaLK @gvwilson - I like a lot of what is discussed in this essay, but no longer think that it integrates well into the materials we have. I think we've done a good job of reorganizing the materials into a tightly focused, cohesive structure and am worried about trying to shoehorn these ideas into that structure. If anyone has ideas about how these specific topics are important to work in, please add a comment. Otherwise, I'll close this when we bring in the revised materials from https://github.com/ErinBecker/instructor-training-reorg/
