### ISSUE TITLE
Add summaries of accessibility guides for lesson material design

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#282]
https://github.com/UKHomeOffice/posters/tree/master/accessibility

**Comment by ErinBecker** [comment]
@gvwilson Rather than attempting to summarize the great content here (it really is great!), I suggest incorporating these as an exercise. 

Example: Trainees work in pairs with one of these guides and suggest one concrete way to improve either the SWC/DC website or a lesson page based on the accessibility guidelines in their guide. This could potentially be a great place to direct trainees to submit their lesson contributions for, as it would provide useful contributions and quickly improve accessibility of our materials. 

Any thoughts? I'm happy to take this on in the next few work cycles. Please let me know if anyone would like to work on this together.

**Comment by ErinBecker** [comment]
Incorporated into checklist (https://github.com/ErinBecker/instructor-training-reorg/issues/45). Closing here.
