### ISSUE TITLE
Example of analogy breaking down.

### ISSUE THREAD

**Issue by mkuzak** [swcarpentry/instructor-training#339]
Add to notes following example when real life analogy breaks down:

A dictionary in real life is ordered alphabetically. When iterating over the elements in python dictionary you cannot expect any particular order. If you want to make sure the order is kept as you want it (not necessarily alphabetical) you need to use special kind of the dictionary (OrderedDict from collections).

**Comment by jttkim** [comment]
Do people necessarily think that being ordered is a necessary property of a dictionary?

Printed dictionaries are lexicographically ordered, sure, but web based dictionaries (I frequently use dict.leo.org, for example) have no perceivable ordering.

The primary property of a dictionary (real, virtual or otherwise) is that it is a mechanism for looking up words, and Python dictionaries meet this criterion. Ordering the words is a secondary measure to enable more efficient lookups -- an implementation detail, if you like.

**Comment by mkuzak** [comment]
@jttkim I see your point. I'm not sure what other people think, but for me "real dictionary" is ordered. I guess I'm just old enough to remember paper dictionaries and the answer will depend on the age of the person you ask. Even for online dictionaries you often have an alphabet at the top of the screen.

**Comment by gvwilson** [comment]
I certainly think a dictionary is ordered - it always confused me that 
Python called something that could be out of order the same thing.

**Comment by cgates** [comment]
On the third hard, if I were going to compare OrderedDict to a physical dictionary I would feel obliged to point out that the OrderedDict is not actually sorting the keys, merely remembering the order in which they were inserted.

**Comment by mkuzak** [comment]
@cgates agreed, that should be stated too.

**Comment by lexnederbragt** [comment]
Just came across this, just had to link to it: http://csteachingtips.org/tip/emphasize-difference-between-terms-may-have-similar-meaning-english-not-code

**Comment by ErinBecker** [comment]
If anyone feels this would incorporate well into the re-organized materials, please add a comment (and/or a PR :-)). Else, I'll close this based on inactivity when we merge the reorganized materials later this month.
