### ISSUE TITLE
Incorporate feedback on self-efficacy

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#341]
Look at comments on http://www.datacarpentry.org/blog/self-efficacy/ and incorporate into instructor training.

**Comment by ErinBecker** [comment]
The comments to the post are below:

Great post! It expresses everything that I often struggle to explain to people who think "If you really need skill/tool/method to do your research, you will learn it/overcome the barriers. If you still need help at the start, this means this skill/tool/method is not for you and so we should't bother making it easier for you.". This elitist attitude proliferates across (e-)research!

If there is a problem with learner success I'd recommend surveying the students' experience before and after the course. I would look at in particular the student's experience especially with operating systems. I suggest you want to know if people who only have ever used say windows get value from your course, or is it too much of a transition? Pay attention to nuts and bolts first. Are users of some operating systems having so much trouble connecting to wifi or some resource that they get behind and rattled when the class starts? Are you requiring them to use telnet or ftp when they never use that in real life so it's a whole hurdle right there? If so then work on testing those things before the class. Is there another way to distribute materials without using legacy methods? I would never myself expect any users to run virtual machines to do class material. I have been on the receiving end of that and if that is happening in any classes I'd highly recommend not doing it. Dealing with some goofy vm where you accidentaly hit some key and you are in bonkers mode is a whole layer of hassle that is being imposed on a student and it definitely needs to be taken into account if comparing one student against another student. In short, I'd really look at the basics before invoking grit or self-efficacy or similar psychological traits.

Hi retireded, I agree with your suggestions. When I attended my first SWC workshop I had trouble connecting to the wifi (I use a Mac), and got terribly behind. I'm the type of person who doesn't give up though, so I went home after the workshop and completed the entire lesson on my own and got through it just fine. That's one reason I'm so glad we make our lessons free and open.

I still think it's important for students to understand self-efficacy as a construct in general. I don't think we should necessarily give all students a Psych 101 crash course, but encouraging them to ask for help, seek out mentors, and find ways to deal with their anxiety is very healthy.

Another important component of whether or not you feel you "can" is instructor attitude:

1. Was the instructor open about how (s)he was confident that each and every student could succeed in the course?
2. Did the instructor start by sharing the challenges (s)he faced when learning this material, and how (s)he got over them?

Or did the class start with an outlining of prerequisites and barriers to entry that you should have overcome?

Darya, I LOVE what you wrote here! I'm an engineer by training, and nearly ALL of my instructors began the course with a rundown of the syllabus and the "I don't take late work" warning. It's fine because yes, we need to know what to expect in the course, but had I known there were other people, especially professors, who had struggles with the material, it would've made me not doubt myself so much.

I'm an adjunct professor now and one of the things I tell my students all the time is, guess what? I struggled at first too, but here is what I did!

Thanks for reading:)

Encouraging students to create "programming pairs/triples" from adjacent neighbors might provide them with an instant peer group of learners. Also, having them briefly describe their research areas together with encouragement by the instructor to reseat themselves next to others in their field might also help in this regard. The reseating could be done, for example, after the first break.

You're absolutely right. We do this in our workshops throughout the 2-days. It can be a challenge though because we are so programmed to work on our own, so when it's time to turn to your neighbor (think-pair-share), there's a reluctancy.

I really like these suggestions. I'm going to pass them along to our instructor training director. Thanks for reading!

You made me want to take the class just to see if it was as bad as you say it is! (Not to the tune of several thousand dollars though). 
Seriously is optimization that weird? Does it have to be that weird that people might fall off their chairs in the first class?

I believe you. I have attended classes where for one thing I think the instructor wanted some people to drop the class so they made the class sound as horrible as possible. Hopefully those days are over with a new concern about degree completion and more emphasis on the students welfare.

I think more could be done with a class that could scare people to death like that. They need to find out why it doesn't look like a logical extension of classes the students have already taken as prerequisites. They're either going to have to think like a student or ... ask the students about first impressions and how they could be improved.

It's about all perspective. For some, and maybe even for you, the class may not have been that bad. People are intimidated by different things. You're right, I wouldn't pay a few grand just to try it out though:)

I'm so happy that times have changed in many instances, and the general population of educators actually want students to succeed.

I really like your suggestions in the last paragraph, because as it stands, students only have the opportunity to give that type of feedback during the end of course evaluation. What good does that really do?

Thanks again for all your valuable comments.

Nice post! I agree specially with the "bring-a-friend" advice: it works great with some type of people.

I have also one minor suggestion. The reference to the book is pretty obscure for anybody not growing up as a child in the US, which the case for a fair part, if not the majority, of the people attending our workshops. Maybe you could add a link to the book's wikipedia page to make it a bit more accesible.

There's no way I would've gotten through undergrad without my best friend. We literally took every class together and studied together all the time. We're best friends to this day, and it all started with two African American women who were the only ones like them in their major (Mechanical Engineering) who were DETERMINED to make it through.

Thank you so much for making that suggestion. I'm realizing now how large our community is and that we truly are global. Not everyone read the book:)

Here's the wiki page if you hadn't found it: https://en.wikipedia.org/wi...

Definitely agree with the need to link to https://en.wikipedia.org/wi... This isn't a book that most people without an English-speaking background grow up with - although an anecdotal survey shows Aussies and Brits do know it as well, not just Americans.

Thank you also Darya for posting the link. I learn something new everyday!

**Comment by ErinBecker** [comment]
Plans to incorporate grit and self-efficacy into next lesson release. For more details see [this outline](https://docs.google.com/document/d/1t2W8PKu78KtTX92qdhqclYGljAbLiWfhza7qH6s1088/edit).
