### ISSUE TITLE
Improve/expand instructor notes

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/instructor-training#385]
As per the March 2nd 1st meeting, here are some thoughts about the [Instructor Notes](http://swcarpentry.github.io/instructor-training/guide/). The goal would be to make it easier for all of us, but especially new instructor trainers, to get started teaching TTT workshops.

* split into different pages
  * per-episode advice/tips (how to teach this theoretical thing) (this I need most :-) )
  * the 'Big Picture' stuff as general background
  * checklists before and after workshops, checkout procedures
  * general advice on technical issues with online teaching, etherpad, how to do exercises etc
* maybe split it out of the lesson repo/website

**Comment by ChristinaLK** [comment]
We've got a lot of this information in the instructor's notes already, I think the initial task will be reorganizing + then adding.  

Personally, I like the idea of having a parallel set of "episodes" that have the exact same formatting/etc as the episode pages but under a different heading (like "teaching notes").  I want to say that it shouldn't be more than 1-2 days work with the current template but I don't have enough time to promise that I could make that happen.  ;)  

If we really figure this out, this might be a good model to pass on to the regular lessons, because this is a common request for those as well.

**Comment by raynamharris** [comment]
Thanks for the suggestions @lexnederbragt and @ChristinaLK. 

I think I mostly agree. Here's my two cents:
1. **Keep on the instructors notes page**: checklists, links to messages or other resources, logistics section
2.**Move elsewhere**: episode-specific notes. I personally think they should be moved to the corresponding episodes, maybe in a call out box called "instructor notes" or incorporated into the main text body, but I'm okay with a whole other section of documents
3.**New content**: I think we could add a section called "Our Trainer's Notes" where every single certified trainer could link to a single mardown file or repo of markdown files containing their own personal teaching notes. This would give everyone a place to store and share teaching notes. This may not be ideal for everyone, but [my notes are here](https://raw.githubusercontent.com/raynamharris/SWC_teachingnotes/master/RaynasInstructorNotes.md)

**Comment by lexnederbragt** [comment]
Thanks for your note, @raynamharris, this is going to be very useful.

2) Not sure a callout box per episode is a good solution as we kind-of want to hide these notes (at least initially) from trainees (I think).

**Comment by ChristinaLK** [comment]
Agree w/ @lexnederbragt re: hiding notes (hence my initial suggestion) but I like the proposed division of material.

**Comment by ErinBecker** [comment]
Similar discussion here: https://github.com/ErinBecker/instructor-training-reorg/issues/17

**Comment by ErinBecker** [comment]
Some of this is in progress here: https://docs.google.com/document/d/1TadkK6IhqhfxbCBxkDVtAmIx1rtdA0tDMIP9PsF0Bro/edit. To be incorporated as instructor notes in this repo or as a Trainer manual in the [Trainers repo](https://github.com/carpentries/trainers). Closing this issue here and added to checklist.
