### ISSUE TITLE
Suggest watching a video of a SWC/DC workshop? 

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/instructor-training#386]
We usually have a mix of learners who have and have not been to a SWC/DC workshop before. Sometimes this isn't a problem, but sometimes it is. 

I wonder if I would be beneficial to suggest in the [welcome email](https://github.com/swcarpentry/instructor-training/blob/gh-pages/files/messages/welcome.txt) that people watch a video of one of our workshops before coming to the training. We could say something like just watch these 15 minutes or something to make it a small commitment. There are a lot of videos here: https://software-carpentry.org/lessons/

**Comment by amoskane** [comment]
Hi! I went to add this in but the link to the videos is already there--

**Comment by mkuzak** [comment]
@amoskane I cannot see it in the [welcome email](https://github.com/swcarpentry/instructor-training/blob/gh-pages/files/messages/welcome.txt)

**Comment by amoskane** [comment]
Line 17, in the **In order to prepare:** section: 
2.  Please go to the Software Carpentry lessons page (http://software-carpentry.org/lessons/) and the Data Carpentry lessons page (http://www.datacarpentry.org/lessons/), have a look at what we currently teach, and then choose *one episode* from the list at the bottom of this message and read through it carefully. You will be using your selected episode for several in-class exercises, so be sure you are comfortable with the content.

**Comment by mkuzak** [comment]
@amoskane this part of the email tells to look at available lessons but not to watch the sample of recorded workshop, which is the topic of this issue

**Comment by ErinBecker** [comment]
@raynamharris, I think this is a great idea. Would you mind putting in a PR?

**Comment by ErinBecker** [comment]
Added to checklist. Closing here.
