### ISSUE TITLE
Allow certification of your 'own' trainees

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/instructor-training#392]
In #384, one of the directions added was that "trainers should not certify people from the workshops they taught", to which @ErinBecker reacted with ["why not?"](https://github.com/swcarpentry/instructor-training/pull/384#issuecomment-283445650). 

This made me rethink the issue. When I am teaching a university course I am also examining my 'own' students. So I now am of the opposite opinion: we should be allowed to certify (i.e. do teaching demo's and discussion sessions) trainees that attended workshops we taught.

Please vote up or down.

**Comment by mkuzak** [comment]
I don't have anything against certifying people we taught.
It actually could cause difficulty in arranging the demo sessions (with up to 4 trainers doing online training).

**Comment by JasonJWilliamsNY** [comment]
I like the idea of someone else certifying. For me and the learner it should contribute to the process being more objective and uniform. That said, it perhaps does not have to be a policy. I would definitely be more supportive for dropping the policy if I felt confident that the checkout procedure (e.g. the teaching demo) had a very objective rubric. Should a there be a scoring system where how points are deducted/added are clear to the learner and instructor? 

Sorry if I am not clarifying things.  +0

**Comment by mkuzak** [comment]
+1 for rubric

**Comment by raynamharris** [comment]
I don't have anything against certifying people we taught.

**Comment by kariljordan** [comment]
+1 for rubric, but I see no problem certifying someone that was in my workshop.

**Comment by ErinBecker** [comment]
https://github.com/swcarpentry/instructor-training/issues/394 For discussion of rubric

**Comment by arokem** [comment]
+1 for a rubric

-1 for the original suggestion. 

I like having others certify people I've instructed. There are a couple of reasons for that: 

1. It gives new instructors exposure to more members of the SWC community. This showcases the community's strength (we are legion!), and also lets people hear a different approach to the one they heard during the instructor training workshop. 

2. This is minor, but I sometimes have potential COI, because I teach people that I want to then teach at workshops I organized. Better to just avoid that.

**Comment by karinlag** [comment]
This rule was instituted to avoid splintering of the community. The thought was that some institutions might acquire their own trainers, people who might not have been part of the SWC/DC community before they became trainers. If they then were also able to certify their own trainees, it might cause them to basically fraction off into a separate "island" of SWC/DC that had little contact with the rest of the community. It would leave SWC/DC central with no way of checking on what those trainees had be taught, which might open up for them to be SWC/DC in name, but not in spirit, so to speak.

I realize that this might sound kind of paranoid, but I'd rather leave this one in place as a way of future proofing our organization. 

Also, +1 for rubric.

**Comment by weaverbel** [comment]
I am +1 to @arokem's views. I would prefer fresh eyes on people I have trained and I like the idea that they meet more of the Carpentry community worldwide, not just people in Australia,

**Comment by maneesha** [comment]
What do we mean when we say "certify" here?  

We know that to get certified they have to do 4 things:
1.  Attend the training workshop.  Only the trainers can attest to whether they've passed this step.
2. Participate in  a discussion session
3. Teach a demo lesson
4. Submit a lesson contribution

For steps 2-4, are we suggesting that trainees must do these steps with someone other than their original trainers?

Actually marking someone "certified" and issuing them a badge is always done by @ErinBecker who will do so based on our team members attesting that steps 2-4 were satisfactorily completed -- even if @ErinBecker has never actually seen this person, correct?  So in the end, in order to complete all four steps, a trainee will likely have had contact with multiple people during the checkout process.  Do we want to enforce that step 2 & step 3 are done in a session that's not run by the original trainers?

**Comment by ChristinaLK** [comment]
+1 to original trainer is not the one who evaluates the demo.  

Scheduling could be an issue, but having switched to regular demo sessions, I think it shouldn't be too bad.

**Comment by karinlag** [comment]
With "certify" I always thought of the person running no 3, i.e. the demo lesson. I believe that is always presented as the last step in the process, and I think that is the most telling one, when it comes to whether the person would be a good SWC/DC instructor. For my part, the other ones can be done with anyone. 

Logistically, I suggest we leave it to the trainees, as we do today. They are much more likely to remember who they trained with, than us remembering who we trained. I don't think it's a big deal if somebody forgets and/or chooses to go to a demo lesson set up by the person they trained with, but I don't think we should have that as a "publically ok" alternative, if you understand what I mean.  That also means that I don't think we need to put up a big technical framework to check that this isn't happening.

**Comment by weaverbel** [comment]
@maneesha I think the original trainer could sign off on someone's contribution to a discussion session but I agree with @ChristinaLK that the evaluation of the teaching demo should be done by someone else.

**Comment by ErinBecker** [comment]
Given this discussion, I'll leave the language on our Etherpad for lesson demos (http://pad.software-carpentry.org/teaching-demos) as is now: "Please don't sign up for a teaching demo with the trainer that trained you." Logistically, we'll leave it to the trainees, as @karinlag says.
