### ISSUE TITLE
Expand material on situated learning

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#44]
The more I think about what we say and what our goals are, the more I think that situated learning describes our view of teaching much better than cognitivism.  We should therefore talk in detail about [communities of practice](https://en.wikipedia.org/wiki/Community_of_practice) and the [zone of proximal development](https://en.wikipedia.org/wiki/Zone_of_proximal_development), both with respect to learners in the classroom and with respect to trainee instructors learning better teaching methods.

**Comment by apawlik** [comment]
Communities of practice is certainly what we do within the instructor community (jugyokenkyu). With regards to people coming to the workshops I'd argue that it varies. In cases when people sign up in groups/with friends (which we encourage), I think that works. With individuals, they may be already a part of a community of practice in their local lab. Though it's likely that their community of practice is similar to ones across similar labs or even the whole domain.
One of the reasons our workshops are popular is because we understand (better or worse) these communities of practice and the way we teach resonates well with them.

A lot of research has been done about fostering communities of practice (and lots of companies pumped lots on money into this - because they would love to create communities of practice top down...except that it's not possible). I think we could talk about successful fostering (we are doing a pretty good job with the instructor community, I think).

When it comes to our workshop learners, Andy Brass at the University of Manchester has some good story to tell based on the two cohorts of MSc Clinical Bioinformatics students who we taught in 2014 and 2015.

**Comment by ChristinaLK** [comment]
In my re-write of the notes, I think I make a distinction between cognitivism as the explicit content of the instructor training course (impacting things like lesson design, etc.) and situated learning as the philosophy underlying the training itself (and software/data carpentry workshops).  Cognitivist ideas drive "how" we teach; situated learning drives what we teach and why we teach.  And in the case of instructor training, the sharing of ideas is perhaps even more important than in a SWC/DC workshop - I've (tried to) reframe the whole training around the idea of community knowledge sharing.  

Does that make sense?  I haven't read much on situated learning, so I'm just throwing words out here right now...

**Comment by gvwilson** [comment]
@ChristinaLK are you willing/able to add a couple of paragraphs in 02-terms about this?

**Comment by ChristinaLK** [comment]
working on it.

**Comment by gvwilson** [comment]
Closed by 7b3c50e
