### ISSUE TITLE
Motivation: Mindset section

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/instructor-training#466]
This section notes:

> Studies have also shown that the simple action of telling learners about the different mindsets before a course can improve learning outcomes for the whole group.

Can we link to some studies that show this?

**Comment by ChristinaLK** [comment]
I have a copy of the "Mindset" book -- I'll try to remember to look this up.

**Comment by maneesha** [comment]
Thanks @ChristinaLK 
I find it frustrating anytime I read "Studies show...." without any reference to the actual studies or research.

**Comment by mkuzak** [comment]
I also have a copy, but it turned out to be more difficult to find than I expected. In this publication: https://ed.stanford.edu/sites/default/files/manual/dweck-walton-cohen-2014.pdf
on page 16 there is a table which cites multiple studies showing the effects of teaching students that intelligence can be developed (a growth mindset).

**Comment by ChristinaLK** [comment]
I looked this up and couldn't find the specific reference.  So maybe take this out for now?

**Comment by ErinBecker** [comment]
This line has been taken out in the new version of this episode: https://github.com/ErinBecker/instructor-training-reorg/blob/gh-pages/_episodes/09-mindset.md
