### ISSUE TITLE
Cover VI/VIM during training

### ISSUE THREAD

**Issue by NBKingsley** [swcarpentry/instructor-training#487]
To ensure that instructors know how to help learners exit the VI or VIM text editor, please cover it during instructor training.

**Comment by raynamharris** [comment]
Thanks for the suggestion @NBKingsley. 

We currently do not teach anything computational during instructor training. One reason is because our instructors teach such diverse computational topics (unix, r, git, python, sql, hpc, spreadsheets, matlab, make, etx.) and come with such diverse computational experience that it doesn't make sense to teach computational technique in this instructor training workshops. 

If you look at the goal of the instructor training workshop, it is two fold: 1) introduce research findings and show how they can be used to help people learn better and faster  2) Introduce the philosophy and teaching practices that have been adopted by the Software and Data Carpentry communities.

That being said, it does make a lot of sense for the "instructor notes" or the github issues of say the Unix lesson would be a good place for an explanation of how to exit VI or VIM in case a learner choses to use that text editor during a workshop.

**Comment by ivanov** [comment]
> in case a learner choses to use that text editor during a workshop.

That choice is made for the learner when making a commit in git if they don't specify their commit message with `-m` - not only is it the default text editor in unix-like systems, it is also installed with git on windows.

**Comment by lexnederbragt** [comment]
This came up during a week-long instructor training where I taught the beginning of the git lesson to have trainees 'experience' a workshop. I suggested this issue to be submitted to the instructor training repo, but agree that it would be better to add this information to the instructor notes for the unix and git lessons.

**Comment by ErinBecker** [comment]
Thanks for the suggestion @NBKingsley and discussion @raynamharris, @ivanov, and @lexnederbragt. I put in  issues referencing this one in the shell-novice and git-novice repos. Closing here.
