### ISSUE TITLE
Cut the live coding exercise in half

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#74]
1.  Do the pipe-and-filter live coding demo.
2.  Ask trainees to teach only the second half, i.e., only the pipes part, not the redirect part.

**Comment by ChristinaLK** [comment]
I can't remember if we discussed this or not - what are we going to do for Data Carpentry instructors who don't necessarily need to know shell?  

As an aside, I had the three shell-averse participants in my last training go through some of the Open Refine lesson...

**Comment by gvwilson** [comment]
Good point - @tracykteal, what do you suggest?

**Comment by apawlik** [comment]
I agree with @ChristinaLK comments. During the demo we *want* the trainees to actually follow what we do (to be students) so if the demo is on shell, we have a problem with those trainees who are on Windows and don't have GitBash or similar. 
I am currently doing live demo with Python using Jupyter. Those who have Jupyter installed, just fire it up. For the rest, I ask them to go to  SageMath where you can run Jupyter on the cloud. Works well. I am able, on my own, to get everyone ready in about 5 min for the demo and people are fine with it (using the cloud). Even those trainees who don't know Python are OK - I teach (demo) as if I had novices in the room.

Yes, indeed, then there is a question of whether we want the trainees to teach the same thing.
Now, because of the variety of trainees coming to the IT I do:
1) Day 1 - Teaching As Performance Art - we watch a *part* of the SciPy video with live coding lesson; we do a round of feedback.
2) Day 1 Homework: I ask them to prep 5 min from a lesson of their choice; for those who don't have much programming background I encourage them to pick up Open Refine. I tell them that the key thing is  that they teach live coding (or using software in case of OR)
3) Day 2 Demo session - I do Python on Jupyter as above. Then they go away in their video groups to record the 5 mins they prepped as homework.

In essence, I don't predefine what they must teach in the last video. It also helps them to prep for the Checkout Procedure (I think). The caveat is to explain why they can't submit the video from the last session instead of doing the live Checkout Procedure (it just occurred to me now - Greg, sorry I didn't mention that at our call, I just didn't connect the dots).
