### ISSUE TITLE
HLW 4: How Do Students Develop Mastery

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#94]

**Comment by lexnederbragt** [comment]
_05-expertise_

* explains in depth differences between novice (or competent practitioner) and experts
* briefly treats expert blind spot
   * I consider this aspect quite important and would spend some time on it during training, maybe asking trainees to come up with an example of how an expert reveals his/her blind-spot by the answer given to a learner's question - and contrasting it to an answers 'at the level' of the learner

_06-memory_

* treats cognitive load, beyond what is discussed in HWL 4
* uses faded examples instead of worked examples as scaffolding tool

_Not treated_

* stages in development of mastery
   * I think discussing figure 4.2 from HWL would be useful
* transfer of knowledge/skills
  * I think there is great potential in workshops to connect the lessons, e.g. 'we just learned how to loop over files in python, can you contrast that to how we did it in the shell previously'? If we ever end up using the GapMinder data for more lessons, connecting them will be easier as well
