### ISSUE TITLE
SoL 1: How Do Students Understand New Ideas?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#95]

**Comment by anelda** [comment]
From SOL - "Teachers often use multiple modalities to convey an idea; for example, they 
will speak while showing a graphic. If teachers take care to ensure that the 
two types of information complement one another — such as showing an 
animation while describing it aloud — learning is enhanced. But if the two 
sources of information are split — such as speaking aloud with different text 
displayed visually — attention is divided and learning is impaired."

We had a comment from the instructor trainees at our workshop that our trainer's explanations went to waste during one of the sections because she was displaying some of the instructor trainer lesson material (text) behind her and people in the class were rather reading the text than listening to her explanations.

Another time she showed the video clip where the teacher asked people a question and then asked the same question again after allowing for some group discussion. During the video everyone in our workshop were focusing intently, listened to the explanation afterwards, and also participated in the conversation that ensued after the explanation.   I thought this was great.

Not sure how to apply this to instructor training, but we've often had discussions about what should be presented on the screen while you're teaching - the lesson material, only your bash screen or Jupyter notebook or the etherpad... 

Maybe we should just draw attention to the fact that it really matters what's on the screen when you're teaching? (This doesn't feel very helpful but maybe some discussion around this will lead to something more concrete?)

**Comment by anelda** [comment]
From SOL: "Students learn new ideas by reference to ideas they already know."

We often just jump in at the beginning of a lesson (Python, R, Shell...) with introduction to the tool that will be taught, but hardly ever the dataset. I always get the learners to open the dataset in Excel so that they can think about the dataset as they see it in Excel as we slice and dice in R or extract lines in bash.
When I introduce them to functions in R I open an Excel spreadsheet and type `=sum( ` upon which the arguments that should be provided appear. This helps them to understand that they actually already use functions in Excel without even knowing it.

Could the idea of starting with something that people know maybe be added as a mention in the concept mapping episode?
