### ISSUE TITLE
HLW 6: Why Do Student Development and Course Climate Matter for Student Learning

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#96]

**Comment by anelda** [comment]
Greg's new video [1] will do well to explain how course climate are set by the instructor and could be added to the motivation/demotivation lesson [2] with an opportunity for people to discuss the video

[1] https://www.youtube.com/watch?v=-ApVt04rB4U
[2] http://swcarpentry.github.io/instructor-training/17-motivation/

**Comment by anelda** [comment]
The feedback that we take before lunch and close of day on the green/red stickies are incredibly valuable and useful and help to set the course climate. If course instructors do not address the suggestions for what can be improved "red stickies", it could create a  mistrust (? my English is letting me down here) relationship between learners who have suggestions and the instructor.

It's important to help new instructors to deal with positive and negative feedback during the workshop. 

During our instructor training workshop we captured all the stickies in a document. I would like to share the feedback with our instructor trainees and ask them how they think one can respond to the feedback. It will help them to understand what kind of feedback to expect and also to provide better feedback themselves when asked for it - something that can be acted on:

For example - if someone is saying the room is too dark, when you return to the venue after tea, acknowledge that the room might be too dark for people and try to adjust lightning so that it is better based on feedback from the class. It takes a few minutes to do that, but for the person who gave the feedback, it means they were heard and will probably give them the courage to give feedback again in future (even if you can't do anything about the lightning - at least acknowledge before continuing with the lesson)

Maybe we can ask a few people to submit their feedback to a repo (it's already anonymous - I'd be happy to upload ours) and provide it as basis for an exercise in giving and receiving feedback? I know - you're going to ask what should we take out :-)
