### ISSUE TITLE
SoL 4: How Does Learning Transfer to New Situations In or Outside of the Classroom

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#97]

**Comment by raynamharris** [comment]
# Summary of this key question

1. The transfer of knowledge to a novel problem **requires both knowledge of the problem’s context and an understanding of the underlying structure**. Teachers should ensure that students have sufficient background knowledge to appreciate the context of a problem

2. We understand new ideas via examples, but it’s often hard to see the unifying underlying
concepts in different examples. Teachers can use multiple examples to help students perceive and remember the underlying structure. For multi-step problems, have students label each step to visualize the structure and breakdown the problem.

**Comment by raynamharris** [comment]
# Where this is covered in the SWC curriculum

##  03-models.md

### Assessing Mental Models
How can we, in-class, know whether the learners already understand this topic (so that the class can move on), and if not, what misconceptions and gaps in their knowledge to address? Summative and formative assessment.

## 05-expertise.md

### Concept maps
Our tool of choice to represent an expert's knowledge graph is the concept map. A concept map is simply a picture of someone's mental model of a domain

## 06-memory.md

### Faded Examples
Faded examples work because they introduce the problem-solving strategy piece by piece. At each step, learners have one new problem to tackle. This is less intimidating than a blank screen or a blank sheet of paper. It also encourages learners to think about the similarities and differences between various approaches, which helps create the linkages in the mental model that instructors want them to form.
